const trucks = [
  {
    id: 1,
    name: "Birria-Landia",
    cuisine: "Mexican",
    location: "Jackson Heights, Queens",
    emoji: "🌮",
    menuUrl: "https://www.instagram.com/birrialandia/",
  },
  {
    id: 2,
    name: "Mysttik Masala",
    cuisine: "Indian",
    location: "Midtown Manhattan",
    emoji: "🍛",
    menuUrl: "https://www.mysttikmasala.com/",
  },
  {
    id: 3,
    name: "The Halal Guys",
    cuisine: "Middle Eastern",
    location: "53rd & 6th Ave, Manhattan",
    emoji: "🥙",
    menuUrl: "https://thehalalguys.com/",
  },
  {
    id: 4,
    name: "NY Dosas",
    cuisine: "Vegetarian",
    location: "Washington Square Park",
    emoji: "🫓",
    menuUrl: "https://www.nydosas.com/",
  },
  {
    id: 5,
    name: "Jerk Pan",
    cuisine: "Jamaican",
    location: "Crown Heights, Brooklyn",
    emoji: "🍗",
    menuUrl: "https://www.instagram.com/jerkpannyc/",
  },
  {
    id: 6,
    name: "Tong",
    cuisine: "Bangladeshi",
    location: "Kensington, Brooklyn",
    emoji: "🍲",
    menuUrl: "https://www.instagram.com/tongfoodtruck/",
  },
  {
    id: 7,
    name: "King Souvlaki of Astoria",
    cuisine: "Greek",
    location: "Astoria, Queens",
    emoji: "🥗",
    menuUrl: "https://www.instagram.com/kingsouvlakinyc/",
  },
  {
    id: 8,
    name: "Ling's Sweet Mini Cakes",
    cuisine: "Chinese",
    location: "Flushing, Queens",
    emoji: "🎂",
    menuUrl: "https://www.instagram.com/lingsminicakes/",
  },
  {
    id: 9,
    name: "Uncle Gussy's",
    cuisine: "Greek",
    location: "Park Ave & 51st St",
    emoji: "🫕",
    menuUrl: "https://www.uncleguysys.com/",
  },
  {
    id: 10,
    name: "Patacon Pisao",
    cuisine: "Venezuelan",
    location: "Lower East Side",
    emoji: "🫔",
    menuUrl: "https://www.instagram.com/patacon_pisao_nyc/",
  },
  {
    id: 11,
    name: "Mom's Momo",
    cuisine: "Tibetan",
    location: "Jackson Heights, Queens",
    emoji: "🥟",
    menuUrl: "https://www.instagram.com/momsmomo_nyc/",
  },
  {
    id: 12,
    name: "Makina Cafe",
    cuisine: "Ethiopian",
    location: "Harlem, Manhattan",
    emoji: "🫙",
    menuUrl: "https://makinacafe.com/",
  },
];

export default trucks;
